services:
    httpd:
        image: httpd:2.4
        container_name: apache
        ports:
            - 8080:80
        volumes:
            - '.:/usr/local/apache2/htdocs/'
        networks:
            - cesi_network
    db:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'cesi'
            MYSQL_PASSWORD: 'cesi'
            MYSQL_ROOT_PASSWORD: 'cesi_root'
        ports:
            - 3306:3306
        volumes:
            - 'db_cesi:/var/lib/mysql/'
        networks:
            - cesi_network
volumes:
    db_cesi:
networks:
    cesi_network: