services:
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
    networks:
      - web_network
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app/api
    environment:
      - ENVIRONMENT=development
    networks:
      - web_network
      - db_network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cesi
    volumes:
      - ./database:/data/db
    networks:
      db_network:
        ipv4_address: 172.21.0.2
networks:
  web_network:
  db_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
