services:
    front-end: 
        image: node:latest
        container_name: front-end
        working_dir: /usr/src/app
        networks: 
            - cesi_network
        volumes: 
            - ./frontend:/usr/src/app
        ports: 
            - "5173:3000"
        command: sh -c "npm install && npm start"
        environment:
            - NODE_ENV=development
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: cesi
        volumes:
            - db_cesi:/data/db
        networks:
            - cesi_network
volumes:
    db_cesi:
networks:
    cesi_network:
